apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops-project-2025
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/kin1m0d/devops-project-2025"
    targetRevision: HEAD
    path: complete-devops-project-time-printer
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true